use super::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) enum Token {
  Begin,
  Break,
  Case,
  Comma,
  Continue,
  Default,
  Delete,
  Do,
  Else,
  End,
  For,
  Function,
  Getline,
  Identifier(String),
  If,
  In,
  Integer(String),
  LBrace,
  LParen,
  Next,
  Print,
  Printf,
  RBrace,
  RParen,
  Return,
  Semicolon,
  String(String),
  Switch,
  While,
}

impl Display for Token {
  fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
    match self {
      Self::Begin => write!(f, "BEGIN"),
      Self::Break => write!(f, "break"),
      Self::Case => write!(f, "case"),
      Self::Comma => write!(f, ","),
      Self::Continue => write!(f, "continue"),
      Self::Default => write!(f, "default"),
      Self::Delete => write!(f, "delete"),
      Self::Do => write!(f, "do"),
      Self::Else => write!(f, "else"),
      Self::End => write!(f, "END"),
      Self::For => write!(f, "for"),
      Self::Function => write!(f, "function"),
      Self::Getline => write!(f, "getline"),
      Self::Identifier(identifier) => write!(f, "{identifier}"),
      Self::If => write!(f, "if"),
      Self::In => write!(f, "in"),
      Self::Integer(integer) => write!(f, "{integer}"),
      Self::LBrace => write!(f, "{{"),
      Self::LParen => write!(f, "("),
      Self::Next => write!(f, "next"),
      Self::Print => write!(f, "print"),
      Self::Printf => write!(f, "printf"),
      Self::RBrace => write!(f, "}}"),
      Self::RParen => write!(f, ")"),
      Self::Return => write!(f, "return"),
      Self::Semicolon => write!(f, ";"),
      Self::String(string) => write!(f, "\"{string}\""),
      Self::Switch => write!(f, "switch"),
      Self::While => write!(f, "while"),
    }
  }
}
